# Generated by Django 2.0.2 on 2018-02-12 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=100)),
                ('country', models.CharField(default='United States', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('state', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)], db_index=True, default=0)),
                ('checkin', models.DateField(db_index=True)),
                ('checkout', models.DateField()),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Guest')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20)),
                ('room_type', models.CharField(choices=[('Regular', 'Regular'), ('Deluxe', 'Deluxe'), ('Suite', 'Suite')], db_index=True, default='Regular', max_length=100)),
                ('room_desc', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=100)),
                ('country', models.CharField(default='United States', max_length=100)),
                ('timezone', models.CharField(max_length=100)),
                ('disabled', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='venue',
            unique_together={('name', 'address', 'city', 'country')},
        ),
        migrations.AddField(
            model_name='room',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Venue'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Room'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Venue'),
        ),
        migrations.AlterUniqueTogether(
            name='guest',
            unique_together={('name', 'address', 'city', 'country')},
        ),
        migrations.AddField(
            model_name='calendar',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Reservation'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Room'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Venue'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['venue', 'room_number'], name='core_room_venue_i_9b5772_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('venue', 'room_number')},
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['guest', 'venue', 'room'], name='core_reserv_guest_i_c8a6a3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('guest', 'venue', 'room')},
        ),
        migrations.AddIndex(
            model_name='calendar',
            index=models.Index(fields=['venue', 'room', 'day'], name='core_calend_venue_i_ba5982_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='calendar',
            unique_together={('venue', 'room', 'day')},
        ),
    ]
